export const STATUS = {
  DRAFT: "Draft",
  PENDING_RECEIVE: "Pending Receive",
  PENDING_STOCK_IN: "Pending Stock In",
  PENDING_CLAIM: "Pending Claim",
  RECEIVED: "Received",
  CANCELLED: "Cancelled",
};

export const RETURN_STATUS = {
  DRAFT: "Draft",
  SUBMITTED: "Submitted",
  APPROVED: "Approved",
  WAITING_REPLACEMENT: "Waiting Replacement",
  REJECTED: "Rejected",
  COMPLETED: "Completed",
  CANCELLED: "Cancelled",
};

export const paymentModeOptions = [
  { value: "pay_after_check", label: "Pay After Check" },
  { value: "prepaid", label: "Prepaid" },
  { value: "partial_prepaid", label: "Partial Prepaid" },
];

export const paymentStatusOptions = [
  { value: "unpaid", label: "Unpaid" },
  { value: "partial", label: "Partial" },
  { value: "paid", label: "Paid" },
];

export const deliveryOptions = [
  { value: "none", label: "None" },
  { value: "supplier_delivery", label: "Supplier Delivery" },
  { value: "self_pickup", label: "Self Pickup" },
  { value: "third_party", label: "Third Party Delivery" },
];

export const deliveryPaidByOptions = [
  { value: "buyer", label: "Buyer" },
  { value: "supplier", label: "Supplier" },
];

export const initialSuppliers = [
  {
    id: 1,
    supplierCode: "SUP-001",
    name: "Thai Huot Trading",
    contactPerson: "Sok Dara",
    phone: "0887193924",
    trustMode: "pay_after_check",
    note: "High-trust supplier. Pay after checking goods.",
  },
  {
    id: 2,
    supplierCode: "SUP-002",
    name: "Mengly Wholesale",
    contactPerson: "Mengly",
    phone: "0887193925",
    trustMode: "prepaid",
    note: "Low-trust supplier. Prepayment required.",
  },
];

export const initialVariantUnits = [
  {
    id: 1,
    productName: "Coca-Cola",
    variantName: "Coca-Cola Can 330ml",
    variantCode: "COKE-CAN-330",
    unitName: "Case",
    baseUnit: "Can",
    conversionQty: 24,
    defaultCost: 7.2,
    isExpirable: true,
  },
  {
    id: 2,
    productName: "Coca-Cola",
    variantName: "Coca-Cola Big Bottle 1.5L",
    variantCode: "COKE-BTL-1500",
    unitName: "Case",
    baseUnit: "Bottle",
    conversionQty: 6,
    defaultCost: 5.1,
    isExpirable: true,
  },
  {
    id: 3,
    productName: "Face Mask",
    variantName: "Face Mask Box",
    variantCode: "MASK-BOX",
    unitName: "Set",
    baseUnit: "Box",
    conversionQty: 6,
    defaultCost: 2.7,
    isExpirable: true,
  },
  {
    id: 4,
    productName: "Sugar",
    variantName: "Sugar Loose",
    variantCode: "SUGAR-LOOSE",
    unitName: "Kg",
    baseUnit: "Gram",
    conversionQty: 1000,
    defaultCost: 0.75,
    isExpirable: false,
  },
  {
    id: 5,
    productName: "Dove Shampoo",
    variantName: "Dove Shampoo 250ml",
    variantCode: "DOVE-250",
    unitName: "Box",
    baseUnit: "Bottle",
    conversionQty: 12,
    defaultCost: 18,
    isExpirable: true,
  },
  {
    id: 6,
    productName: "Instant Noodle",
    variantName: "Instant Noodle Chicken Box",
    variantCode: "NOODLE-CHICKEN-BOX",
    unitName: "Box",
    baseUnit: "Pack",
    conversionQty: 30,
    defaultCost: 9.5,
    isExpirable: true,
  },
];

export const initialPurchases = [
  {
    id: 1,
    purchaseNo: "PUR-001",
    supplierId: 1,
    supplierName: "Thai Huot Trading",
    createdBy: "Admin",
    purchaseDate: "2026-05-01",
    paymentMode: "pay_after_check",
    paymentStatus: "unpaid",
    subtotal: 1368,
    discountTotal: 0,
    deliveryOption: "supplier_delivery",
    deliveryFee: 2,
    deliveryFeeCurrency: "USD",
    deliveryPaidBy: "buyer",
    grandTotal: 1370,
    paidAmount: 0,
    balanceAmount: 1370,
    note: "Pay after check. Supplier brought 200 Case, 10 damaged, shop accepts and pays only 190 Case.",
    status: STATUS.PENDING_STOCK_IN,
    createdAt: "2026-05-01",
    updatedAt: "2026-05-01",
    items: [
      {
        id: 101,
        variantUnitId: 1,
        productName: "Coca-Cola",
        variantName: "Coca-Cola Can 330ml",
        variantCode: "COKE-CAN-330",
        unitName: "Case",
        baseUnit: "Can",
        conversionQty: 24,
        invoicedQty: 200,
        paidQty: 190,
        receivedQty: 200,
        acceptedQty: 190,
        damagedQty: 10,
        claimQty: 0,
        unitCost: 7.2,
        unitCostBase: 0.3,
        lineTotal: 1368,
        expiredDate: "2026-12-31",
      },
    ],
  },
  {
    id: 2,
    purchaseNo: "PUR-002",
    supplierId: 2,
    supplierName: "Mengly Wholesale",
    createdBy: "Admin",
    purchaseDate: "2026-05-02",
    paymentMode: "prepaid",
    paymentStatus: "paid",
    subtotal: 270,
    discountTotal: 0,
    deliveryOption: "self_pickup",
    deliveryFee: 0,
    deliveryFeeCurrency: "USD",
    deliveryPaidBy: "buyer",
    grandTotal: 270,
    paidAmount: 270,
    balanceAmount: 0,
    note: "Prepaid purchase. Paid for 100 Set, 10 Set arrived damaged, supplier claim required.",
    status: STATUS.PENDING_CLAIM,
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    items: [
      {
        id: 201,
        variantUnitId: 3,
        productName: "Face Mask",
        variantName: "Face Mask Box",
        variantCode: "MASK-BOX",
        unitName: "Set",
        baseUnit: "Box",
        conversionQty: 6,
        invoicedQty: 100,
        paidQty: 100,
        receivedQty: 100,
        acceptedQty: 90,
        damagedQty: 10,
        claimQty: 10,
        unitCost: 2.7,
        unitCostBase: 0.45,
        lineTotal: 270,
        expiredDate: "2026-10-10",
      },
    ],
  },
  {
    id: 3,
    purchaseNo: "PUR-003",
    supplierId: 2,
    supplierName: "Mengly Wholesale",
    createdBy: "Admin",
    purchaseDate: "2026-05-04",
    paymentMode: "prepaid",
    paymentStatus: "paid",
    subtotal: 37.5,
    discountTotal: 0,
    deliveryOption: "third_party",
    deliveryFee: 1.5,
    deliveryFeeCurrency: "USD",
    deliveryPaidBy: "buyer",
    grandTotal: 39,
    paidAmount: 39,
    balanceAmount: 0,
    note: "Prepaid before goods arrive. Waiting for supplier delivery.",
    status: STATUS.PENDING_RECEIVE,
    createdAt: "2026-05-04",
    updatedAt: "2026-05-04",
    items: [
      {
        id: 301,
        variantUnitId: 4,
        productName: "Sugar",
        variantName: "Sugar Loose",
        variantCode: "SUGAR-LOOSE",
        unitName: "Kg",
        baseUnit: "Gram",
        conversionQty: 1000,
        invoicedQty: 50,
        paidQty: 50,
        receivedQty: 0,
        acceptedQty: 0,
        damagedQty: 0,
        claimQty: 0,
        unitCost: 0.75,
        unitCostBase: 0.00075,
        lineTotal: 37.5,
        expiredDate: "",
      },
    ],
  },
];

export const initialPurchaseReturns = [
  {
    id: 1,
    purchaseReturnNo: "PRET-001",
    purchaseId: 2,
    purchaseNo: "PUR-002",
    supplierId: 2,
    supplierName: "Mengly Wholesale",
    returnDate: "2026-05-03",
    returnType: "partial_return",
    returnReason: "damaged",
    resolutionType: "replacement",
    resolutionStatus: "submitted",
    subtotal: 27,
    note: "10 Set Face Mask arrived damaged after prepaid purchase. Request replacement from supplier.",
    status: RETURN_STATUS.SUBMITTED,
    createdBy: "Admin",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    resolvedAt: null,
    items: [
      {
        id: 1001,
        purchaseReturnId: 1,
        purchaseItemId: 201,
        variantUnitId: 3,
        productName: "Face Mask",
        variantName: "Face Mask Box",
        variantCode: "MASK-BOX",
        unitName: "Set",
        baseUnit: "Box",
        conversionQty: 6,
        qtyReturned: 10,
        baseQtyReturned: 60,
        unitCost: 2.7,
        unitCostBase: 0.45,
        lineTotal: 27,
        condition: "damaged",
        stockAction: "no_stock_change",
        reason: "Damaged before stock in. No stock deduction because only accepted quantity entered inventory.",
      },
    ],
  },
];

