export const initialSales = [
  {
    id: 1,
    saleNo: "INV-001",
    customerId: null,
    customerName: "Walk-in",
    cashierName: "Sokha",
    saleType: "retail",
    saleChannel: "pos",
    invoiceCurrency: "USD",
    exchangeRateKhrPerUsd: 4000,
    saleDate: "2026-05-01",
    displayDate: "01 May 2026",
    subtotal: 12.5,
    discountTotal: 0,
    deliveryRequired: false,
    deliveryOption: "customer_pickup",
    deliveryFee: 0,
    deliveryFeeCurrency: "USD",
    deliveryAddress: "",
    deliveryStatus: "none",
    grandTotal: 12.5,
    saleStatus: "completed",
    paymentStatus: "paid",
    isPrinted: true,
    printedAt: "2026-05-01 10:15",
    note: "Walk-in retail sale.",
    items: [
      {
        id: 101,
        productNameSnapshot: "Coca-Cola",
        variantNameSnapshot: "Coca-Cola Can 330ml",
        unitNameSnapshot: "Can",
        qty: 5,
        baseQty: 5,
        unitPrice: 0.5,
        discountType: "none",
        discountValue: 0,
        discountAmount: 0,
        lineSubtotal: 2.5,
        lineTotal: 2.5,
      },
      {
        id: 102,
        productNameSnapshot: "Face Mask",
        variantNameSnapshot: "Face Mask Box",
        unitNameSnapshot: "Box",
        qty: 2,
        baseQty: 2,
        unitPrice: 5,
        discountType: "none",
        discountValue: 0,
        discountAmount: 0,
        lineSubtotal: 10,
        lineTotal: 10,
      },
    ],
    payments: [
      {
        id: 1001,
        paymentMethod: "cash",
        providerName: "Cash",
        currencyCode: "USD",
        amountReceived: 12.5,
        exchangeRateUsed: 4000,
        amountAppliedInvoiceCurrency: 12.5,
        changeAmount: 0,
        changeCurrency: "USD",
        referenceNo: "",
        paidAt: "2026-05-01 10:15",
      },
    ],
    returns: [],
  },
  {
    id: 2,
    saleNo: "INV-002",
    customerId: 1,
    customerName: "Dara Mini Mart",
    cashierName: "Nita",
    saleType: "wholesale",
    saleChannel: "phone_order",
    invoiceCurrency: "USD",
    exchangeRateKhrPerUsd: 4000,
    saleDate: "2026-05-01",
    displayDate: "01 May 2026",
    subtotal: 140,
    discountTotal: 5,
    deliveryRequired: true,
    deliveryOption: "shop_delivery",
    deliveryFee: 2,
    deliveryFeeCurrency: "USD",
    deliveryAddress: "Kandal province",
    deliveryStatus: "delivered",
    grandTotal: 137,
    saleStatus: "completed",
    paymentStatus: "paid",
    isPrinted: true,
    printedAt: "2026-05-01 14:20",
    note: "Wholesale customer. Delivered by shop.",
    items: [
      {
        id: 201,
        productNameSnapshot: "Coca-Cola",
        variantNameSnapshot: "Coca-Cola Can 330ml",
        unitNameSnapshot: "Case",
        qty: 20,
        baseQty: 480,
        unitPrice: 7,
        discountType: "amount",
        discountValue: 5,
        discountAmount: 5,
        lineSubtotal: 140,
        lineTotal: 135,
      },
    ],
    payments: [
      {
        id: 2001,
        paymentMethod: "mobile_payment",
        providerName: "ABA",
        currencyCode: "USD",
        amountReceived: 100,
        exchangeRateUsed: 4000,
        amountAppliedInvoiceCurrency: 100,
        changeAmount: 0,
        changeCurrency: "USD",
        referenceNo: "ABA-29302",
        paidAt: "2026-05-01 14:20",
      },
      {
        id: 2002,
        paymentMethod: "cash",
        providerName: "Cash",
        currencyCode: "KHR",
        amountReceived: 148000,
        exchangeRateUsed: 4000,
        amountAppliedInvoiceCurrency: 37,
        changeAmount: 0,
        changeCurrency: "KHR",
        referenceNo: "",
        paidAt: "2026-05-01 14:20",
      },
    ],
    returns: [],
  },
  {
    id: 3,
    saleNo: "INV-003",
    customerId: null,
    customerName: "Walk-in",
    cashierName: "Sokha",
    saleType: "retail",
    saleChannel: "pos",
    invoiceCurrency: "USD",
    exchangeRateKhrPerUsd: 4000,
    saleDate: "2026-05-02",
    displayDate: "02 May 2026",
    subtotal: 9.75,
    discountTotal: 0,
    deliveryRequired: false,
    deliveryOption: "customer_pickup",
    deliveryFee: 0,
    deliveryFeeCurrency: "USD",
    deliveryAddress: "",
    deliveryStatus: "none",
    grandTotal: 9.75,
    saleStatus: "completed",
    paymentStatus: "refunded",
    isPrinted: true,
    printedAt: "2026-05-02 09:30",
    note: "Refunded because customer returned damaged item.",
    items: [
      {
        id: 301,
        productNameSnapshot: "Dove Shampoo",
        variantNameSnapshot: "Dove Shampoo 250ml",
        unitNameSnapshot: "Bottle",
        qty: 3,
        baseQty: 3,
        unitPrice: 3.25,
        discountType: "none",
        discountValue: 0,
        discountAmount: 0,
        lineSubtotal: 9.75,
        lineTotal: 9.75,
      },
    ],
    payments: [
      {
        id: 3001,
        paymentMethod: "cash",
        providerName: "Cash",
        currencyCode: "USD",
        amountReceived: 9.75,
        exchangeRateUsed: 4000,
        amountAppliedInvoiceCurrency: 9.75,
        changeAmount: 0,
        changeCurrency: "USD",
        referenceNo: "",
        paidAt: "2026-05-02 09:30",
      },
    ],
    returns: [
      {
        id: 1,
        salesReturnNo: "SR-001",
        returnType: "full_return",
        resolutionType: "refund",
        totalAmount: 9.75,
        reason: "Damaged product",
        status: "completed",
        createdAt: "2026-05-02",
      },
    ],
  },
  {
    id: 4,
    saleNo: "INV-004",
    customerId: 2,
    customerName: "Sokha Mart",
    cashierName: "Admin",
    saleType: "wholesale",
    saleChannel: "online",
    invoiceCurrency: "USD",
    exchangeRateKhrPerUsd: 4000,
    saleDate: "2026-05-03",
    displayDate: "03 May 2026",
    subtotal: 80,
    discountTotal: 0,
    deliveryRequired: true,
    deliveryOption: "third_party_delivery",
    deliveryFee: 3,
    deliveryFeeCurrency: "USD",
    deliveryAddress: "Phnom Penh",
    deliveryStatus: "pending",
    grandTotal: 83,
    saleStatus: "confirmed",
    paymentStatus: "partial",
    isPrinted: false,
    printedAt: "",
    note: "Partial payment. Waiting delivery.",
    items: [
      {
        id: 401,
        productNameSnapshot: "Face Mask",
        variantNameSnapshot: "Face Mask Box",
        unitNameSnapshot: "Set",
        qty: 20,
        baseQty: 120,
        unitPrice: 4,
        discountType: "none",
        discountValue: 0,
        discountAmount: 0,
        lineSubtotal: 80,
        lineTotal: 80,
      },
    ],
    payments: [
      {
        id: 4001,
        paymentMethod: "mobile_payment",
        providerName: "ABA",
        currencyCode: "USD",
        amountReceived: 50,
        exchangeRateUsed: 4000,
        amountAppliedInvoiceCurrency: 50,
        changeAmount: 0,
        changeCurrency: "USD",
        referenceNo: "ABA-33211",
        paidAt: "2026-05-03 11:00",
      },
    ],
    returns: [],
  },
];

export const weeklyChartData = [
  { day: "SUN", amount: 2800 },
  { day: "MON", amount: 1200 },
  { day: "TUE", amount: 1500 },
  { day: "WED", amount: 1800 },
  { day: "THU", amount: 900 },
  { day: "FRI", amount: 3400 },
  { day: "SAT", amount: 200 },
];


